# Scientific tools - Numpy

- numpy : outils d'analyse numérique (matrice, algebre linéaire, optimisation ...)
- matplotlib : librairie de tracé de graph - utilise numpy
- pandas : outils d'analyse de données (traitement, filtre, fusion ...)

## numpy
Numpy fournit des functions permettant de facilement faire des opérations matricielles
le tableau est le type de base 

## creation

- créer avec des valeurs

In [6]:
import numpy as np
un_vecteur=np.array([1,2,3])

print(f"vecteur : \n {un_vecteur}")
print(f"type : {type(un_vecteur)}")


vecteur : 
 [1 2 3]
type : <class 'numpy.ndarray'>


In [ ]:
une_matrice= np.array([
    [1, 2, 3],
    [4, 5, 6],
    [6, 7, 9],
])
print(f"matrice : \n {une_matrice}")
print(f"type : {type(une_matrice)}")

- génère des valeurs

In [ ]:
suite=np.arange(10)
print(f"suite : \n {suite}")

In [ ]:
x_set=np.arange(2, 3, 0.1)
print(f"x_set : \n {x_set}")

In [ ]:
identite=np.eye(3)
print(f"identite : \n {identite}")

In [ ]:
#j'explore:
# - np.linspace
# - np.zeros
# - np.ones
# - np.diag

- lecture de fichier csv

In [4]:
donnees = np.loadtxt('simple.csv', delimiter = ',', skiprows = 1) 
print(f"donnees : \n {donnees}")

donnees : 
 [[0. 0.]
 [1. 1.]
 [2. 4.]
 [3. 9.]]


# Operation

In [18]:
# multiplication éléments par éléments
a=np.arange(9).reshape(3,3)
b=np.arange(9,18).reshape(3,3)
print("a : \n",a)
print("b : \n",b)
print("a*b : \n",a*b)


a : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
b : 
 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]
a*b : 
 [[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


In [38]:
v=np.arange(9,12).reshape(3,1)
print(v)
print(a*v)

[[ 9]
 [10]
 [11]]
[[ 0  9 18]
 [30 40 50]
 [66 77 88]]


In [ ]:
#tester multiplication matricielle
